name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  test:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - run: echo "Reusable workflow picked up by runner!"
