name: runner test
on: workflow_dispatch

jobs:
  test:
    runs-on:
      - self-hosted
      - Windows
      - X64
    steps:
      - name: hello world
        run: echo "hello from self-hosted runners!!!"

